# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FileSystem.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 720)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.CurrentPathLabel = QtWidgets.QLabel(self.groupBox_2)
        self.CurrentPathLabel.setObjectName("CurrentPathLabel")
        self.verticalLayout.addWidget(self.CurrentPathLabel)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.FileListWidget = QtWidgets.QListWidget(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FileListWidget.sizePolicy().hasHeightForWidth())
        self.FileListWidget.setSizePolicy(sizePolicy)
        self.FileListWidget.setObjectName("FileListWidget")
        self.verticalLayout.addWidget(self.FileListWidget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ReturnToParentButton = QtWidgets.QPushButton(self.groupBox_2)
        self.ReturnToParentButton.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ReturnToParentButton.sizePolicy().hasHeightForWidth())
        self.ReturnToParentButton.setSizePolicy(sizePolicy)
        self.ReturnToParentButton.setObjectName("ReturnToParentButton")
        self.horizontalLayout.addWidget(self.ReturnToParentButton)
        self.NewFileButton = QtWidgets.QPushButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.NewFileButton.sizePolicy().hasHeightForWidth())
        self.NewFileButton.setSizePolicy(sizePolicy)
        self.NewFileButton.setObjectName("NewFileButton")
        self.horizontalLayout.addWidget(self.NewFileButton)
        self.NewDirectoryButton = QtWidgets.QPushButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.NewDirectoryButton.sizePolicy().hasHeightForWidth())
        self.NewDirectoryButton.setSizePolicy(sizePolicy)
        self.NewDirectoryButton.setObjectName("NewDirectoryButton")
        self.horizontalLayout.addWidget(self.NewDirectoryButton)
        self.FormatButton = QtWidgets.QPushButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FormatButton.sizePolicy().hasHeightForWidth())
        self.FormatButton.setSizePolicy(sizePolicy)
        self.FormatButton.setObjectName("FormatButton")
        self.horizontalLayout.addWidget(self.FormatButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3.addWidget(self.groupBox_2)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.TextSize = QtWidgets.QLabel(self.groupBox)
        self.TextSize.setObjectName("TextSize")
        self.verticalLayout_2.addWidget(self.TextSize)
        self.PlainTextEdit = QtWidgets.QPlainTextEdit(self.groupBox)
        self.PlainTextEdit.setEnabled(False)
        self.PlainTextEdit.setObjectName("PlainTextEdit")
        self.verticalLayout_2.addWidget(self.PlainTextEdit)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.SaveButton = QtWidgets.QPushButton(self.groupBox)
        self.SaveButton.setEnabled(False)
        self.SaveButton.setObjectName("SaveButton")
        self.horizontalLayout_2.addWidget(self.SaveButton)
        self.CancelButton = QtWidgets.QPushButton(self.groupBox)
        self.CancelButton.setEnabled(False)
        self.CancelButton.setObjectName("CancelButton")
        self.horizontalLayout_2.addWidget(self.CancelButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3.addWidget(self.groupBox)
        self.horizontalLayout_3.setStretch(0, 1)
        self.horizontalLayout_3.setStretch(1, 2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.SaveAndExitButton = QtWidgets.QPushButton(self.centralwidget)
        self.SaveAndExitButton.setObjectName("SaveAndExitButton")
        self.verticalLayout_3.addWidget(self.SaveAndExitButton)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "文件系统管理"))
        self.groupBox_2.setTitle(_translate("MainWindow", "文件管理"))
        self.CurrentPathLabel.setText(_translate("MainWindow", "当前目录：/"))
        self.label.setText(_translate("MainWindow", "文件类型"))
        self.label_2.setText(_translate("MainWindow", "文件名"))
        self.ReturnToParentButton.setText(_translate("MainWindow", "返回上层"))
        self.NewFileButton.setText(_translate("MainWindow", "新建文件"))
        self.NewDirectoryButton.setText(_translate("MainWindow", "新建目录"))
        self.FormatButton.setText(_translate("MainWindow", "格式化"))
        self.groupBox.setTitle(_translate("MainWindow", "文件编辑"))
        self.TextSize.setText(_translate("MainWindow", "文本文件大小（打开文件时）："))
        self.SaveButton.setText(_translate("MainWindow", "保存"))
        self.CancelButton.setText(_translate("MainWindow", "放弃"))
        self.SaveAndExitButton.setText(_translate("MainWindow", "保存并退出系统"))
