# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'memory_management.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1280, 720)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.CommandList = QtWidgets.QListWidget(self.groupBox)
        self.CommandList.setObjectName("CommandList")
        self.verticalLayout.addWidget(self.CommandList)
        self.horizontalLayout_8.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.CommandLog = QtWidgets.QListWidget(self.groupBox_2)
        self.CommandLog.setObjectName("CommandLog")
        self.verticalLayout_3.addWidget(self.CommandLog)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.horizontalLayout_8.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        spacerItem = QtWidgets.QSpacerItem(20, 180, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem)
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox_4.setObjectName("groupBox_4")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.FIFOButton = QtWidgets.QRadioButton(self.groupBox_4)
        self.FIFOButton.setEnabled(True)
        self.FIFOButton.setChecked(True)
        self.FIFOButton.setObjectName("FIFOButton")
        self.horizontalLayout_2.addWidget(self.FIFOButton)
        self.LRUButton = QtWidgets.QRadioButton(self.groupBox_4)
        self.LRUButton.setEnabled(True)
        self.LRUButton.setObjectName("LRUButton")
        self.horizontalLayout_2.addWidget(self.LRUButton)
        self.horizontalLayout_9.addLayout(self.horizontalLayout_2)
        self.verticalLayout_5.addWidget(self.groupBox_4)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.TotalCommand = QtWidgets.QSpinBox(self.groupBox_3)
        self.TotalCommand.setMinimum(10)
        self.TotalCommand.setMaximum(10000)
        self.TotalCommand.setProperty("value", 320)
        self.TotalCommand.setObjectName("TotalCommand")
        self.horizontalLayout_4.addWidget(self.TotalCommand)
        self.label_5 = QtWidgets.QLabel(self.groupBox_3)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.PageCommand = QtWidgets.QSpinBox(self.groupBox_3)
        self.PageCommand.setMinimum(1)
        self.PageCommand.setMaximum(10000)
        self.PageCommand.setProperty("value", 10)
        self.PageCommand.setObjectName("PageCommand")
        self.horizontalLayout_5.addWidget(self.PageCommand)
        self.label_6 = QtWidgets.QLabel(self.groupBox_3)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_5.addWidget(self.label_6)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.TotalPage = QtWidgets.QSpinBox(self.groupBox_3)
        self.TotalPage.setMinimum(1)
        self.TotalPage.setMaximum(10000)
        self.TotalPage.setProperty("value", 4)
        self.TotalPage.setObjectName("TotalPage")
        self.horizontalLayout_6.addWidget(self.TotalPage)
        self.label_7 = QtWidgets.QLabel(self.groupBox_3)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_6.addWidget(self.label_7)
        self.verticalLayout_5.addLayout(self.horizontalLayout_6)
        self.GenerateCommandButton = QtWidgets.QPushButton(self.groupBox_3)
        self.GenerateCommandButton.setObjectName("GenerateCommandButton")
        self.verticalLayout_5.addWidget(self.GenerateCommandButton)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.ExecuteOneButton = QtWidgets.QPushButton(self.groupBox_3)
        self.ExecuteOneButton.setEnabled(False)
        self.ExecuteOneButton.setObjectName("ExecuteOneButton")
        self.horizontalLayout_3.addWidget(self.ExecuteOneButton)
        self.ExecuteFiveButton = QtWidgets.QPushButton(self.groupBox_3)
        self.ExecuteFiveButton.setEnabled(False)
        self.ExecuteFiveButton.setObjectName("ExecuteFiveButton")
        self.horizontalLayout_3.addWidget(self.ExecuteFiveButton)
        self.ExecuteAllButton = QtWidgets.QPushButton(self.groupBox_3)
        self.ExecuteAllButton.setEnabled(False)
        self.ExecuteAllButton.setObjectName("ExecuteAllButton")
        self.horizontalLayout_3.addWidget(self.ExecuteAllButton)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.PageLackText = QtWidgets.QLabel(self.groupBox_3)
        self.PageLackText.setObjectName("PageLackText")
        self.horizontalLayout_7.addWidget(self.PageLackText)
        self.PageLackCounter = QtWidgets.QLabel(self.groupBox_3)
        self.PageLackCounter.setObjectName("PageLackCounter")
        self.horizontalLayout_7.addWidget(self.PageLackCounter)
        self.PageLackRadioText = QtWidgets.QLabel(self.groupBox_3)
        self.PageLackRadioText.setObjectName("PageLackRadioText")
        self.horizontalLayout_7.addWidget(self.PageLackRadioText)
        self.PageLackRadio = QtWidgets.QLabel(self.groupBox_3)
        self.PageLackRadio.setObjectName("PageLackRadio")
        self.horizontalLayout_7.addWidget(self.PageLackRadio)
        self.verticalLayout_5.addLayout(self.horizontalLayout_7)
        spacerItem1 = QtWidgets.QSpacerItem(20, 179, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem1)
        self.horizontalLayout_8.addWidget(self.groupBox_3)
        self.horizontalLayout_8.setStretch(0, 1)
        self.horizontalLayout_8.setStretch(1, 4)
        self.horizontalLayout_8.setStretch(2, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "内存管理-请求调页模拟"))
        self.groupBox.setTitle(_translate("MainWindow", "指令序列"))
        self.label.setText(_translate("MainWindow", "序号"))
        self.label_2.setText(_translate("MainWindow", "指令地址"))
        self.groupBox_2.setTitle(_translate("MainWindow", "页面调度信息"))
        self.label_3.setText(_translate("MainWindow", "调页日志"))
        self.groupBox_3.setTitle(_translate("MainWindow", "页面调度控制"))
        self.groupBox_4.setTitle(_translate("MainWindow", "置换算法"))
        self.FIFOButton.setText(_translate("MainWindow", "FIFO"))
        self.LRUButton.setText(_translate("MainWindow", "LRU"))
        self.label_5.setText(_translate("MainWindow", "指令总条数（≥10）"))
        self.label_6.setText(_translate("MainWindow", "单页面指令数"))
        self.label_7.setText(_translate("MainWindow", "分配页面数"))
        self.GenerateCommandButton.setText(_translate("MainWindow", "生成指令序列"))
        self.ExecuteOneButton.setText(_translate("MainWindow", "执行一条"))
        self.ExecuteFiveButton.setText(_translate("MainWindow", "执行五条"))
        self.ExecuteAllButton.setText(_translate("MainWindow", "执行全部"))
        self.PageLackText.setText(_translate("MainWindow", "缺页次数："))
        self.PageLackCounter.setText(_translate("MainWindow", "0"))
        self.PageLackRadioText.setText(_translate("MainWindow", "缺页率："))
        self.PageLackRadio.setText(_translate("MainWindow", "0"))
